export const REQUEST_CURRENCY_EXCHANGE = 'REQUEST_CURRENCY_EXCHANGE';
export const REQUEST_CURRENCY_EXCHANGE_SUCCEEDED = 'REQUEST_CURRENCY_EXCHANGE_SUCCEEDED';
export const REQUEST_CURRENCY_EXCHANGE_FAILED = 'REQUEST_CURRENCY_EXCHANGE_FAILED';

